Milestone345
Victoriyaa/itirod pull request #3
Opened 2020-06-20 22:18 UTC by Victoriyaa

Добрый вечер, высылаю вам версию своего приложения. 
Ссылка, по которому оно доступно - https://group-expenses-kononchuk.herokuapp.com/

Чтобы посмотреть внутренность, необходимо зарегистрироваться. Логика приложения такая - все люди, с одинаковым secret key при регистрации попадают автоматически в одну группу. Поэтому, если вы хотите проверить с помощью уже существующей базы, пожалуйста, укажите код "viktoria", чтобы посмотреть созданную для примера группу.

В приложении есть база данных, поддерживающая всех зарегистрированных пользователей и все внесенные оплаты для пользователей. Указывается баланс для каждого пользователя в группе. Если он положительный, значит пользователь должен такую сумму денег остальным участникам, если он отрицательный - тогда наоборот, такую сумму другие участники группы должны ему.

Также можно посмотреть последнюю активность (внесенные оплаты) и внести собственно новую оплату. При внесении оплаты необходимо указать кто платит, какую сумму и на каких людей ее нужно разбить (указывать через пробел). 

Производится валидация пароля на сложность и проверка электронного адреса при регистрации на корректность. При внесении оплаты, все логины пользователей валидируются. 

Чтобы выйти из аккаунта, можно сверху справа найти соответствующую менюшку.

С уваженением,
Виктория Конончук

2020-09-02 15:21 UTC, gmltA requested changes
Also: task requirements are not fulfilled.

2020-09-02 15:21 UTC, gmltA commented on expenses/static/scripts/validate_email.js
> +    var input = $('.validate-input .input');
No jQuery allowed.

2020-09-02 15:21 UTC, gmltA commented on expenses/static/styles/dashboard.css
> +    max-width: 48px !important;
Try to do it without `!important`

2020-09-02 15:21 UTC, gmltA commented on expenses/templates/add_payment.html
> +    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
Bootstrap is not allowed.

2020-09-02 15:21 UTC, gmltA commented on expenses/templates/add_payment.html
> +            <div class="navi">
Wrong tag.

2020-09-02 15:21 UTC, gmltA commented on expenses/templates/add_payment.html
> +                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
This is not a link.

2020-09-02 15:21 UTC, gmltA commented on expenses/templates/add_payment.html
> +                <h1>&nbsp;</h1>
???

2020-09-02 15:21 UTC, gmltA commented on expenses/templates/add_payment.html
> +                            <label>Payer</label>
Label is not connected to the input.

2020-09-02 15:21 UTC, gmltA commented on expenses/templates/add_payment.html
> +                        <label>*Users must be entered with a space, without payer</label>
This should not be a label.

2020-09-02 15:21 UTC, gmltA commented on expenses/templates/add_payment.html
> +                                    <h2 style="color:Tomato;"><li>{{ message }}</li></h2>
All styling goes into CSS files.

2020-09-02 15:21 UTC, gmltA commented on expenses/templates/dashboard.html
> +                        <th><h1>Full Name</h1></th>
It is not `h1`

2020-09-02 15:21 UTC, gmltA commented on expenses/templates/index.html
> +					<span class="start-form-title">
This tag is also incorrect.

2020-09-02 15:21 UTC, gmltA commented on expenses/templates/index.html
> +						<button class="container-start-form-btn start-form-btn">
`button` is not a valid tag inside `a`.

2020-09-05 16:10 UTC, gmltA requested changes
Why did you mark unresolved problems as resolved?
Deployed version still uses bootstrap CSS. This should also be changed.

2020-09-05 16:10 UTC, gmltA commented on expenses/templates/add_payment.html
> +            <section class="navi">
Still incorrect tag.
```suggestion
            <nav class="navi">
```

2020-09-05 16:10 UTC, gmltA commented on expenses/templates/add_payment.html
> +                                    <div class="dropdown-toggle" data-toggle="dropdown">
A `button` maybe?

2020-09-05 16:10 UTC, gmltA commented on expenses/templates/add_payment.html
> +                <h1></h1><h1><span class="blue"> {{ title }} </span></h1><h1></h1>
Why do you need empty tags here?

2020-09-09 03:52 UTC, Victoriyaa commented
Исправила все Ваши замечания

2020-09-09 10:49 UTC, Victoriyaa commented
Извините, что я делала Resolve conversation, вернула их обратно и не закрывала.

2020-09-10 18:02 UTC, gmltA requested changes

2020-09-10 18:02 UTC, gmltA commented on expenses/static/styles/add_payment.css
> +}
Вы проста скапіравалі код, ці што? У вас адны і тыя ж стылі па некалькі разоў сустракаюцца.

+ вёрстка на `float`ах таксама павінна быць выдалена, а замест яе павінны выкарыстоўвацца flex ці grid.

2020-09-10 18:02 UTC, gmltA commented on expenses/templates/add_payment.html
> +                <h1><span class="blue"> {{ title }} </span></h1>>
Ну вы хоць глядзіце, што вы выдаляеце...

2020-09-10 18:02 UTC, gmltA commented on expenses/templates/add_payment.html
> +<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
І вярнулі назад bootstrap...

2020-09-13 14:40 UTC, gmltA reviewed
`float` з CSS вы так і не выдалілі.

2020-09-13 14:41 UTC, gmltA requested changes
Выдаліце вёрстку на `float`'ах, калі ласка.

2020-09-17 16:01 UTC, gmltA commented
Ну а сайт аднавіць?

2020-09-17 16:57 UTC, Victoriyaa commented
Обновила сайт.

2020-09-18 20:17 UTC, gmltA commented
https://group-expenses-kononchuk.herokuapp.com/

усё яшчэ бачу і bootstrap, i jquery. Здаецца, нешта не аднавілася.

2020-09-18 21:14 UTC, Victoriyaa commented
Удалила везде подключение jQuery и Bootstrap

2020-09-20 08:57 UTC, gmltA requested changes
1. Адсутнічае пераключэнне мовы.
2. На галоўнай старонцы адсутнічаюць сведкі, якія патрабаваліся ў заданні.
3. У форме "Add expense" не хапае дадзеных, якія былі ў заданні (image, split method). Форма ніяк не абвяшчае карыстальніка аб памылках.
4. Адсутнічае магчымасць выдаліць / змяніць транзакцыю.
5. У мабільнай версіі ўвогуле адсутнічае меню.
6. Што гэта за фармат даты такі?
 ![image](https://user-images.githubusercontent.com/138737/93707532-4013c800-fb38-11ea-9bd4-7cc5cd7c4e08.png)
7. Няма магчымасці адзначыць транзакцыю як "payed" — доўг аплачаны.

2020-09-20 09:05 UTC, Victoriyaa commented
Добрый день, 
я думаю, что это уже нереально все исправить, чтобы сдать до конца месяца экзамен, какие у меня есть еще варианты? Можно хоть какую-то часть исправить, и так проект очень большой, я его делала очень очень очень долго и много. Если бы я знала эти правки хотя бы в начале месяца, я бы конструктивно переписала, а так получается каждый день находится новая какая-то правка и приходится многое переделывать

2020-09-20 09:08 UTC, Victoriyaa commented
Я просто уже не успею до конца месяца сдать экзамен, потому что я весь этот месяц что-то исправляю и дальше в ожидании каких-то новых правок.

2020-09-20 09:10 UTC, Victoriyaa commented
Разве у меня настолько плохой проект, что меня нельзя допустить? Я его хотела сдать еще в семестре до экзамена, но это очень объемный проект, я отправила и не успела дождаться даже ваших поправок, после этого правила еще в июне, теперь весь сентябрь... Просто я понимаю, что можно было бы взять какую-то более простую тему и сделать гораздо проще, чем это и вы бы это приняли. Я не забивала на этот проект, сделала работающую версию этого проекта

2020-09-20 09:59 UTC, gmltA commented
Вікторыя, вы нічога не рабілі ўвесь семестр, потым праігнарыравалі палову патрабаванняў і нават не пацікавіліся, што можна зрабіць.

Выканайце зараз першы пункт, а там паглядзім.

2020-09-20 10:00 UTC, gmltA commented
Вікторыя, вы нічога не рабілі ўвесь семестр, потым праігнарыравалі палову патрабаванняў і нават не пацікавіліся, што можна зрабіць, каб палепшыць вашае становішча. А зараз вы лічыце, што проста выбралі складаную тэму?

Выканайце зараз першы пункт, а там паглядзім.

2020-09-20 10:36 UTC, Victoriyaa commented
А кто из тех что сейчас пересдает лабораторные работы, очень работал в семестре?
Я вам честно признаюсь, у меня уже нет каких-то сил что-то переделывать, у меня уже нервы из-за этого проекта и вообще за последний месяц на пределе. Я никогда преподавателям не жаловалась, но в связи с ситуацией по предмету и вообще того что происходит, я пью успокоительные и плачу каждый вечер, мне это честно признаюсь не нравится делать, я делала пол сентября уже через силы, но это не значит что я совсем тупая и не могу работать программистом и делать что-то другое, я уже и в Яндексе работала, мне предлагали там остаться работать и бросить универ, но я осталась учиться. Да, получается не идеально, какие-то предметы плохо идут. Я не не делала весь семестр, просто этот предмет мне не приносил много удовольствия, чтобы над ним все время сидеть, поэтому я закрыла все другие предметы и пересела на ваш. 

Про того что половину требования не выполнила, извините, за это я прошу прощения, но это было сделано неумышленно, может я что-то не то смотрела. 

Я вам прислала работу еще в середине июня, я его писала уже в течении семестра, вы ответили только в этом месяце. Я написала вам еще в июне, это значит что я делала проект еще в семестре, а не как многие, кто просто сел и делал это летом. 

Я честно скажу, я уже не могу что-то исправлять, вы добиваетесь того чтобы меня отчислили? У меня за весь университет было две пересдачи (с этим предметом), я всегда училась и делала до конца, но сейчас у меня есть проблемы гораздо больше чем сидеть и исправлять это.

2020-09-20 12:09 UTC, gmltA commented
Вікторыя, гэта ўсё ніякім чынам не апраўдвае таго, што вы даслалі сваю працу пасля сессіі. Таксама ніякім чынам не апраўдвае таго, што вы неяк не так асэнсавалі заданні. Ад мяне гэта аніякім чынам не залежыла і спрабаваць абвінаваціць у нечым мяне ў вас не атрымаецца. Ніводны чалавек, які звярнуўся да мяне з праблемамі па прадмеце, не атрымаў адмовы. Вам я таксама даю магчымасць зрабіць менш, чым рабілі астатнія студэнты ў межах гэтага задання. У тым, што прадмет вас не зацікавіў, безумоўна, ёсць віна выкладчыкаў і мая асабіста, але і вашых спроб зацікавіцца я таксама не наглядаў.

Паверце, у мяне няма ніякага жадання адлічыць асабіста вас. Але давайце называць усё сваімі словамі: вы забілі на тэрміны выканання заданняў, як і на самі заданні. І вы прапануеце мне зараз зачыніць на ўсё гэта вочы? З такім поспехам можна было лабараторныя не рабіць увогуле.

Таму яшчэ раз: вы можаце выканаць тое, што я прапанаваў, ці не выконваць гэтага. Вынік залежыць толькі ад вас.

P.S. Я не пастаўлю допуск вам без выканання задання, але вы можаце звярнуцца да загадчыка кафедры. Магчыма, яна здолее прыняць іншае рашэнне.

2020-09-20 12:42 UTC, Victoriyaa commented
Хорошо, спасибо тогда вам за разное отношения к разным студентам. Вы сегодня зачли лабу Станиславу Бокуну, в которой по сути ничего не работает, в которой нет даже половины того что сделала я. Все стили поехали, однообразные, веб-версия вообще нифига не работает, кода половины даже нету, куча кнопок не работает, это он работал весь семестр, что вы зачли ему лабу?? И вы ему отвечаете вот так:


![](https://user-images.githubusercontent.com/138737/93708275-91728600-fb3d-11ea-849b-23572b4d2403.png)


Это нормально? Это надо было в шуточку предмет воспринять? Человек признается что ничего не сделал и вы его допускаете ? Он сам написал что ничего по стилям не сделал, а вы ему все зачли, это получается вы всех одинаково оцениваете? И так В КАЖДОМ ВТОРОМ проекте, который вы приняли, есть куча деталей и функционала, который не работают

Видимо они выполнили все требования, а только я, которая сидела ночами писала код, ничего не делала

Я вас до этого ни в чем не винила, но это двоякое отношение к людям, это какое-то уже нечеловеческое отношение. Если бы вы всех одинаково строго принимали, как меня, я бы ничего не сказала и понимала что виновата только я. Почему тогда нельзя было сразу указать на все ошибки, а не исправлять по одному замечанию сто раз?

Ну если пойти к Н.А. Волоровой это единственное решение, то хорошо.

2020-09-20 12:46 UTC, Victoriyaa commented
Я посмотрела, вы приняли у человека С ПЕРВОГО РАЗА, не спросив вообще ничего!!!!! Он прислал вам работу только вчера, это называется одинаковое отношение ко всем студентам? Я считаю, что это очень несправедливо, как мне нужно пошутить тогда, чтобы вы меня приняли? Если нужно, могу мемов сюда покидать

2020-09-20 13:28 UTC, gmltA commented
Вікторыя, вы робіце вельмі непрыгожа, спрабуючы апраўдаць свае памылкі параўнаннем з іншымі людзьмі.

У Стаса амаль цалкам выканана заданне, якое ставілася на лабараторныя. Ён не парушаў тых патрабаванняў, якія былі пастаўленыя да праекту і стылі ў яго напісаныя самастойна. Я веру, што разметку старонкі ён рабіў сам. Вы скапіравалі CSS ці з бутстрапу, ці яшчэ аднекуль. Далей паглядзіце, калі ласка, на функцыянал, які зроблены ў яго, і ізноў на ваш праект. У вас, дарэчы, яшчэ не выканана патрабаванне па рэлізацыі SPA. Вось вам і розныя адносіны.

Не займайцеся больш такімі справамі, калі ласка.

2020-09-21 22:23 UTC, Victoriyaa commented
https://expensesvik.web.app/ - версия приложения, исправила чтобы было SPA и переключение языка.

2020-09-22 08:08 UTC, gmltA approved these changes
Вось і ўсё. Шчыра хочацца верыць, што вы пісалі гэта самастойна.

Яшчэ раз хачу папрасіць прабачэння за тое, што з прадметам пасябраваць у вас не атрымалася.

2020-09-22 20:28 UTC, merged